package model;
// Generated 30/04/2014 09:35:03 PM by Hibernate Tools 3.6.0



/**
 * Editorial generated by hbm2java
 */
public class Editorial  implements java.io.Serializable {


     private String codEditorial;
     private String nombreEditorial;

    public Editorial() {
    }

    public Editorial(String codEditorial, String nombreEditorial) {
       this.codEditorial = codEditorial;
       this.nombreEditorial = nombreEditorial;
    }
   
    public String getCodEditorial() {
        return this.codEditorial;
    }
    
    public void setCodEditorial(String codEditorial) {
        this.codEditorial = codEditorial;
    }
    public String getNombreEditorial() {
        return this.nombreEditorial;
    }
    
    public void setNombreEditorial(String nombreEditorial) {
        this.nombreEditorial = nombreEditorial;
    }




}


