package model;
// Generated 30/04/2014 09:35:03 PM by Hibernate Tools 3.6.0



/**
 * Libro generated by hbm2java
 */
public class Libro  implements java.io.Serializable {


     private String codLibro;
     private String nombreLibro;
     private String autor;
     private String anhoPublicacion;
     private Integer cantidad;
     private String codEditorial;

    public Libro() {
    }

	
    public Libro(String codLibro, String codEditorial) {
        this.codLibro = codLibro;
        this.codEditorial = codEditorial;
    }
    public Libro(String codLibro, String nombreLibro, String autor, String anhoPublicacion, Integer cantidad, String codEditorial) {
       this.codLibro = codLibro;
       this.nombreLibro = nombreLibro;
       this.autor = autor;
       this.anhoPublicacion = anhoPublicacion;
       this.cantidad = cantidad;
       this.codEditorial = codEditorial;
    }
   
    public String getCodLibro() {
        return this.codLibro;
    }
    
    public void setCodLibro(String codLibro) {
        this.codLibro = codLibro;
    }
    public String getNombreLibro() {
        return this.nombreLibro;
    }
    
    public void setNombreLibro(String nombreLibro) {
        this.nombreLibro = nombreLibro;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public String getAnhoPublicacion() {
        return this.anhoPublicacion;
    }
    
    public void setAnhoPublicacion(String anhoPublicacion) {
        this.anhoPublicacion = anhoPublicacion;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public String getCodEditorial() {
        return this.codEditorial;
    }
    
    public void setCodEditorial(String codEditorial) {
        this.codEditorial = codEditorial;
    }




}


